# Generated by Django 2.0.3 on 2018-04-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='notice_board',
            new_name='notice',
        ),
    ]
