# Generated by Django 2.0.3 on 2018-04-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180401_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('NOT_ACTIVE', 'not active')], default='ACTIVE', max_length=10),
        ),
    ]
