# Generated by Django 2.0.3 on 2018-04-01 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_notice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('PRIMARY', 'primary'), ('SECONDARY', 'secondary'), ('SENIOR', 'senior')], default='PRIMARY', max_length=50),
        ),
        migrations.AddField(
            model_name='gallery',
            name='event',
            field=models.CharField(choices=[('NONE', 'none'), ('HAPPY NEW YEAR', 'happy new year'), ('HAPPY HOLI', 'happy holi')], default='NONE', max_length=50),
        ),
        migrations.AddField(
            model_name='gallery',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('NOT_ACTIVE', 'not active')], default='ACTIVE', max_length=10),
        ),
        migrations.AddField(
            model_name='notice',
            name='menu_image_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
