# Generated by Django 2.0.3 on 2018-04-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180401_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='image',
            field=models.ImageField(default='am.jpg', upload_to='C:\\Users\\Jordan\\Desktop\\hansraj_school\\notice_image'),
        ),
    ]
