# Generated by Django 2.0.3 on 2018-04-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_notice_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\Jordan\\Desktop\\hansraj_school\\notice_image'),
        ),
    ]
