# Generated by Django 2.0.6 on 2018-06-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_gallery_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('MEMORIES', 'memories'), ('ACHIEVEMENTS', 'achievements'), ('SUBPRIMARY', 'subprimary'), ('PRIMARY', 'primary'), ('SECONDARY', 'secondary'), ('SENIOR', 'senior')], default='PRIMARY', max_length=50),
        ),
    ]
